name: sinflix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  expandable_text: ^2.3.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  image_picker: ^1.1.2
  logger: ^2.6.0
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  flutter_image_compress: ^2.4.0
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/fonts/EuclidCircularA/
    - assets/images/
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/EuclidCircularA/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/EuclidCircularA/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/EuclidCircularA/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EuclidCircularA/Euclid Circular A Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#000000"
  image: assets/images/SinFlixLogo.png
  background_image: assets/images/SinFlixSplash.png
  android_gravity: center
  ios_content_mode: scaleAspectFill
  fullscreen: true
