// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB8roLaNVWtQyfpCVAfcOU5qq6AeT2moM',
    appId: '1:953723265139:web:fd75f7580ae665de37ca06',
    messagingSenderId: '953723265139',
    projectId: 'sinflix-c6129',
    authDomain: 'sinflix-c6129.firebaseapp.com',
    storageBucket: 'sinflix-c6129.firebasestorage.app',
    measurementId: 'G-TRYJZ595NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslPQ3_McbhkB_DLJT6mjuUsuvJ7qbtlQ',
    appId: '1:953723265139:android:f8bc7025ab038be337ca06',
    messagingSenderId: '953723265139',
    projectId: 'sinflix-c6129',
    storageBucket: 'sinflix-c6129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2c24FlH0jWWCU-mGY_w4rBoGe0ogD9Ik',
    appId: '1:953723265139:ios:c211f0914b316f1037ca06',
    messagingSenderId: '953723265139',
    projectId: 'sinflix-c6129',
    storageBucket: 'sinflix-c6129.firebasestorage.app',
    iosBundleId: 'com.example.popcorndate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2c24FlH0jWWCU-mGY_w4rBoGe0ogD9Ik',
    appId: '1:953723265139:ios:c211f0914b316f1037ca06',
    messagingSenderId: '953723265139',
    projectId: 'sinflix-c6129',
    storageBucket: 'sinflix-c6129.firebasestorage.app',
    iosBundleId: 'com.example.popcorndate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB8roLaNVWtQyfpCVAfcOU5qq6AeT2moM',
    appId: '1:953723265139:web:03c193f600cd6c9737ca06',
    messagingSenderId: '953723265139',
    projectId: 'sinflix-c6129',
    authDomain: 'sinflix-c6129.firebaseapp.com',
    storageBucket: 'sinflix-c6129.firebasestorage.app',
    measurementId: 'G-KSB10HFZ7D',
  );
}
